### ISSUE TITLE
The nonce value "vhkp81fy8e80g8l2k" has already been used

### ISSUE THREAD

**Issue by shabaz-ejaz** [calcinai/xero-php#568]
I've created an auto generating invoice function that has been working fine for so long and then one day I get the following error:

> The nonce value "vhkp81fy8e80g8l2k" has already been used 

Any ideas why this is? Below is the full log:

```
[2019-04-27 10:00:18] production.ERROR: The nonce value "vhkp81fy8e80g8l2k" has already been used {"exception":"[object] (XeroPHP\\Remote\\Exception\\UnauthorizedException(code: 401): The nonce value \"vhkp81fy8e80g8l2k\" has already been used at /srv/users/asianwed/apps/aws-booking-system/public/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php:87)
[stacktrace]
#0 /srv/users/asianwed/apps/aws-booking-system/public/vendor/calcinai/xero-php/src/XeroPHP/Remote/Request.php(127): XeroPHP\\Remote\\Response->parse()
#1 /srv/users/asianwed/apps/aws-booking-system/public/app/Invoice.php(14): XeroPHP\\Remote\\Request->send()
#2 /srv/users/asianwed/apps/aws-booking-system/public/app/Console/Commands/BookingBalanceDueReminderCommand.php(110): App\\Invoice->sendEmail()
#3 /srv/users/asianwed/apps/aws-booking-system/public/app/Console/Commands/BookingBalanceDueReminderCommand.php(54): App\\Console\\Commands\\BookingBalanceDueReminderCommand->createInvoice(Object(App\\Booking))
#4 [internal function]: App\\Console\\Commands\\BookingBalanceDueReminderCommand->handle()
#5 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#10 /srv/users/asianwed/apps/aws-booking-system/public/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#11 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /srv/users/asianwed/apps/aws-booking-system/public/vendor/symfony/console/Application.php(960): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /srv/users/asianwed/apps/aws-booking-system/public/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\BookingBalanceDueReminderCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /srv/users/asianwed/apps/aws-booking-system/public/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /srv/users/asianwed/apps/aws-booking-system/public/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 {main}
"} 
****```

**Comment by timacdonald** [comment]
This is not an issue with the library, but an issue with having already used the nonce, and the Xero API is returning an error to you.

Refer to the official Xero docs: https://developer.xero.com/documentation/auth-and-limits/oauth-issues and look for the heading **Nonce Used (nonce_used)**

**Comment by tobz-nz** [comment]
I get this error occasionally as well.
Isn't the nonce generated by this package? I am not doing it anywhere and everything works most of the time - only occasionally getting this error.

Feels like it IS something to do with with the library.

**Comment by timacdonald** [comment]
Could someone provide a code sample where this error is being triggered for you so we can see what is happening under the hood?

**Comment by tobz-nz** [comment]
Here's a snippet of code from my project:

```
...

$this->xero = new Xero(config('services.xero'));

...

private function createInvoice(Contact $contact, Collection $lineItems, Account $account)
{
    $invoice = new Invoice($this->xero);

    // get invoice tax type
    $taxType = ($this->customer->xero_account_code ?: self::ACCOUNT_CODE) === 201 ?
        TaxType::NEW_ZEALAND_ZERORATED : TaxType::NEW_ZEALAND_OUTPUT2;

    $accountCode = $this->customer->xero_account_code ?: self::ACCOUNT_CODE;

    $lineItems->each(function ($item, $label) use ($invoice, $taxType, $accountCode) {
        $lineItem = new LineItem($this->xero);
        $lineItem
            ->setItemCode(str_replace('_', ' ', $label))
            ->setDescription($this->invoiceable->lineItemDescription($label))
            ->setQuantity(1)
            ->setUnitAmount(abs($item))
            ->setTaxType($taxType)
            ->setAccountCode($accountCode);

        $invoice->addLineItem($lineItem);
    });

    if ($this->fee) {
        $description = (new LineItem($this->xero))
            ->setDescription('Fees')
            ->setLineAmount($this->fee)
            ->setAccountCode(404); // bank fee

        $invoice->addLineItem($description);
    }

    $invoice
        ->setType(Invoice::INVOICE_TYPE_ACCREC)
        ->setContact($contact)
        ->setReference($this->reference)
        ->setUrl($this->url)
        ->setDueDate(Carbon::now()->addDays(14))
        ->setStatus(Invoice::INVOICE_STATUS_AUTHORISED)
        ->save();

    ...
}

...
```

This works fine most of the time.

**Comment by timacdonald** [comment]
Please see this draft PR to try and address the issue. Would be good if you could test this and reply in the comments if it is working as expected for you: https://github.com/calcinai/xero-php/pull/621

**Comment by shabaz-ejaz** [comment]
Not sure how one would accurately test this as it happens occasionally. The tests may pass but when working with real invoices from time to time I did get this problem, out of about 300 invoices generated I got this about twice.

**Comment by timacdonald** [comment]
Although it might be hard to prove, we can always flip it around and try and disprove it. Just to be clear - I am _not_ saying this isn't an issue, and I'm not saying this is a proof in itself, but it is fun to try and play with anyway.

I just generated a 100,000 nonces, all consecutively in a loop (as fast as possible) in the same way the library _currently_ does and all 100,000 are unique (every time I do it).

The issue, as far as I can see, is that somehow (perhaps running multiple background queues) the server is sending multiple requests at the _exact_ same time. Or there could be some other underlying issue that I'm not aware of.

Check out this out: https://3v4l.org/qn0hs

One thing that is interesting is the length of the nonce is coming out at 17 - 18 chars - rather than 20.

That is being run against every version of PHP back till 5.3 (or around there) and never hits a duplicate. (not that the version of PHP is what we think the issue could be).

The new implementation that should get tagged soon is no longer time based, so fingers crossed it will resolve this issue for everyone.

**Comment by shabaz-ejaz** [comment]
I got this error again a few days ago.

Log: 
```

[2019-08-25 10:00:14] production.ERROR: The nonce value "1ykbccieto9w0c9qy" has already been used {"exception":"[object] (XeroPHP\\Remote\\Exception\\UnauthorizedException(code: 401): The nonce value \"1ykbccieto9w0c9qy\" has already been used at /srv/users/asianwed/apps/aws-booking-system/public/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php:87)
[stacktrace]
#0 /srv/users/asianwed/apps/aws-booking-system/public/vendor/calcinai/xero-php/src/XeroPHP/Remote/Request.php(127): XeroPHP\\Remote\\Response->parse()
#1 /srv/users/asianwed/apps/aws-booking-system/public/app/Invoice.php(14): XeroPHP\\Remote\\Request->send()
#2 /srv/users/asianwed/apps/aws-booking-system/public/app/Console/Commands/BookingBalanceDueReminderCommand.php(110): App\\Invoice->sendEmail()
#3 /srv/users/asianwed/apps/aws-booking-system/public/app/Console/Commands/BookingBalanceDueReminderCommand.php(54): App\\Console\\Commands\\BookingBalanceDueReminderCommand->createInvoice(Object(App\\Booking))
#4 [internal function]: App\\Console\\Commands\\BookingBalanceDueReminderCommand->handle()
#5 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#10 /srv/users/asianwed/apps/aws-booking-system/public/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#11 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /srv/users/asianwed/apps/aws-booking-system/public/vendor/symfony/console/Application.php(960): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /srv/users/asianwed/apps/aws-booking-system/public/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\BookingBalanceDueReminderCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /srv/users/asianwed/apps/aws-booking-system/public/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /srv/users/asianwed/apps/aws-booking-system/public/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /srv/users/asianwed/apps/aws-booking-system/public/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 {main}
"} 
```


Code that generates invoices:

```
public function handle()
    {
        
		  // send customer SMS reminder that balance is due on balance_due_date
			 $bookings_balance_due = Booking::completed()->where('balance_due_date', Carbon::now()->format('Y-m-d'))->get();
			 
			 foreach($bookings_balance_due as $booking) {
				 if(!$booking) abort(404);
				 
				 if(!empty(floatval($booking->balance_due))) {
					$this->createInvoice($booking);
				 }
			 }
    }
	
	
	
		
	private function createInvoice($booking) {

		$xero = \App::make('XeroPrivate');
		$invoice = \App::make('XeroInvoice');
		$contact = \App::make('XeroContact');
		$address = \App::make('XeroAddress');
		$line1 = \App::make('XeroInvoiceLine');

		// Set up the invoice contact
		$contact->setContactStatus('ACTIVE');
		$contact->setName($booking->customer_name);
		$contact->setEmailAddress($booking->customer_email);
		$contact->setDefaultCurrency('GBP');
		
		// Assign the contact to the invoice
		$invoice->setContact($contact);

		// Set the type of invoice being created (ACCREC / ACCPAY)
		$invoice->setType('ACCREC');

		$dateInstance = new \DateTime();
		$invoice->setDate($dateInstance);
		$invoice->setDueDate($dateInstance);
		$invoice->setInvoiceNumber('INV-BOOKING-' . $booking->id . ' - ' . uniqid());
		$invoice->setReference('Booking ' . $booking->id);

		$invoice->setCurrencyCode('GBP');
		$invoice->setStatus('AUTHORISED');
		

		// Create some order lines
		$line1->setDescription('Remaining balance for Booking: ' . $booking->id);

		$line1->setQuantity(1);
		$line1->setUnitAmount(floatval($booking->balance_due));
		$line1->setTaxAmount(0);
		$line1->setTaxType('NONE');
		$line1->setLineAmount(floatval($booking->balance_due));
		$line1->setAccountCode(200);
		$line1->setDiscountRate(0); // Percentage

		// Add the line to the order
		$invoice->addLineItem($line1);

		$xero->save($invoice);
		$invoice->sendEmail();
	}
```
