### ISSUE TITLE
Fatal error: Uncaught exception 'XeroPHP\Remote\Exception' with message 'XeroPHP\Models\Accounting\Invoice::$Contact is mandatory and is either missing or empty.' in /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Remote/Model.php:362 Stack trace: #0 /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Application.php(278): XeroPHP\Remote\Model->validate() #1 /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Remote/Model.php(406): XeroPHP\Application->save(Object(XeroPHP\Models\Accounting\Invoice)) #2 /home/active35/opend/public_html/vendor/calcinai/xero-php/src/XeroPHP/public.php(203): XeroPHP\Remote\Model->save() #3 {main} thrown in /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Remote/Model.php on line 362

### ISSUE THREAD

**Issue by Godwin-Richard** [calcinai/xero-php#605]
Fatal error: Uncaught exception 'XeroPHP\Remote\Exception' with message 'XeroPHP\Models\Accounting\Invoice::$Contact is mandatory and is either missing or empty.' in /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Remote/Model.php:362 Stack trace: #0 /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Application.php(278): XeroPHP\Remote\Model->validate() #1 /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Remote/Model.php(406): XeroPHP\Application->save(Object(XeroPHP\Models\Accounting\Invoice)) #2 /home/active35/opend/public_html/vendor/calcinai/xero-php/src/XeroPHP/public.php(203): XeroPHP\Remote\Model->save() #3 {main} thrown in /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Remote/Model.php on line 362

**Comment by Godwin-Richard** [comment]
i am trying to create invoice using the following code 

$invoice = new Invoice($xero);


$invoice->setType('ACCREC')
->setDate(new DateTime())
    ->setDueDate(new DateTime());





$lineItem = new Invoice\LineItem();

$lineItem->setDescription(['Test Invoice'])
    ->setQuantity(['11'])
    ->setAccountCode(['1213'])
    ->setUnitAmount(['2132']);

$invoice->addLineItem($lineItem)->save();


i get the following errror

Fatal error: Uncaught exception 'XeroPHP\Remote\Exception' with message 'XeroPHP\Models\Accounting\Invoice::$Contact is mandatory and is either missing or empty.' in /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Remote/Model.php:362 Stack trace: #0 /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Application.php(278): XeroPHP\Remote\Model->validate() #1 /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Remote/Model.php(406): XeroPHP\Application->save(Object(XeroPHP\Models\Accounting\Invoice)) #2 /home/active35/opend/public_html/vendor/calcinai/xero-php/src/XeroPHP/public.php(203): XeroPHP\Remote\Model->save() #3 {main} thrown in /home/active35/opend/vendor/calcinai/xero-php/src/XeroPHP/Remote/Model.php on line 362
