### ISSUE TITLE
Fatal error: Uncaught XeroPHP\Exception: Class does not exist

### ISSUE THREAD

**Issue by rezasazesh** [calcinai/xero-php#654]
I have seen this error in a few other trends but do not see a solution

I have used the package using composer, in my test file for Xero I have

````
$PathToMainDirectory = "../../";
include_once $PathToMainDirectory . 'conf.php';
include_once $PathToMainDirectory . 'vendor/autoload.php';
include_once 'config.php';

$xero = new \XeroPHP\Application\PrivateApplication($xero_base_config);

$contacts = $xero->load(Contact::class)->execute();

foreach ($contacts as $contact) {
    print_r($contact);
}

````

In config.php I have a sample config as found in example

````
<?php
$xero_base_config = [
    'xero' => [
        // API versions can be overridden if necessary for some reason.
        //'core_version'     => '2.0',
        //'payroll_version'  => '1.0',
        //'file_version'     => '1.0'
    ],
    'oauth' => [
        'callback' => 'oob',
        'consumer_key' => 'k',
        'consumer_secret' => 's',
        //If you have issues passing the Authorization header, you can set it to append to the query string
        //'signature_location'    => \XeroPHP\Remote\OAuth\Client::SIGN_LOCATION_QUERY
        //For certs on disk or a string - allows anything that is valid with openssl_pkey_get_(private|public)
        'rsa_private_key' => 'file://certs/private.pem',
        'rsa_public_key' => 'file://certs/public.pem',
    ],
    //These are raw curl options.  I didn't see the need to obfuscate these through methods
    'curl' => [
        CURLOPT_USERAGENT => 'XeroPHP Test App',
        //Only for partner apps - unfortunately need to be files on disk only.
        //CURLOPT_CAINFO          => 'certs/ca-bundle.crt',
        //CURLOPT_SSLCERT         => 'certs/entrust-cert-RQ3.pem',
        //CURLOPT_SSLKEYPASSWD    => '1234',
        //CURLOPT_SSLKEY          => 'certs/entrust-private-RQ3.pem'
    ],
];

````

I am trying to get started so I did the first example the Docs give which is printing contacts and I get the error below, what should I do? Thanks

````

Fatal error: Uncaught XeroPHP\Exception: Class does not exist [\XeroPHP\Models\Invoice] in /Applications/XAMPP/xamppfiles/htdocs/Novez/vendor/calcinai/xero-php/src/XeroPHP/Application.php:174 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/Novez/vendor/calcinai/xero-php/src/XeroPHP/Remote/Query.php(58): XeroPHP\Application->validateModelClass('\\XeroPHP\\Models...') #1 /Applications/XAMPP/xamppfiles/htdocs/Novez/vendor/calcinai/xero-php/src/XeroPHP/Application.php(280): XeroPHP\Remote\Query->from('Invoice') #2 /Applications/XAMPP/xamppfiles/htdocs/novez/integrations/xero/test.php(10): XeroPHP\Application->load('Invoice') #3 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/Novez/vendor/calcinai/xero-php/src/XeroPHP/Application.php on line 174

````

**Comment by calcinai** [comment]
Are you correctly importing namespaces (with a `use`)
