### ISSUE TITLE
Fatal error related to GuzzleHTTP get_message_body_summary()

### ISSUE THREAD

**Issue by FrankEBailey** [calcinai/xero-php#790]
Hi, I keep getting this error since migrating to the oAuth 2.0 version of PHP. 

It seems to be related to the get_message_body_summary() function in Guzzle being deprecated, but the stack trace isn't showing where the call is coming from so I have no idea how to fix this. Can anyone help me please?

```
<b>Fatal error</b>:  Uncaught Error: Call to undefined function GuzzleHttp\Psr7\get_message_body_summary() in C:\inetpub\xero-new\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:127
Stack trace:
#0 C:\inetpub\xero-new\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php(107): GuzzleHttp\Exception\RequestException::getResponseBodySummary(Object(GuzzleHttp\Psr7\Response))
#1 C:\inetpub\xero-new\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#2 C:\inetpub\xero-new\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 C:\inetpub\xero-new\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#4 C:\inetpub\xero-new\v in <b>C:\inetpub\xero-new\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php</b> on line <b>127</b>
```

**Comment by FrankEBailey** [comment]
Redownloading the entire Xero-PHP codebase has resolved this issue, Guzzle might've been the wrong version.
