### ISSUE TITLE
Error fetching contact by contact ID

### ISSUE THREAD

**Issue by abhimanusharma** [calcinai/xero-php#805]
I am also facing error while getting a single contact.

I have `scopes accounting.transactions accounting.contacts` added in my request.

My $xero is returning the xero object successfully.
but code
`$contact = $xero->loadByGUID(Contact::class, $guid);`

is returning error.

```
XeroPHP\Remote\Exception\ForbiddenException: You are not permitted to access this resource in /var/www/html/project_dev/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php:127
Stack trace:
#0 /var/www/html/project_dev/vendor/calcinai/xero-php/src/XeroPHP/Remote/Request.php(119): XeroPHP\Remote\Response->parse()
#1 /var/www/html/project_dev/vendor/calcinai/xero-php/src/XeroPHP/Application.php(200): XeroPHP\Remote\Request->send()
#2 /var/www/html/project_dev/vendor/langleyfoxall/xero-laravel/src/Wrappers/QueryWrapper.php(102): XeroPHP\Application->loadByGUID('\\XeroPHP\\Models...', 'xxxxxxxx-xxxx-x...')
```

**Comment by calcinai** [comment]
Are you attempting to load a contact with the GUID `xxxxxxxx-xxxx-x...`?

**Comment by abhimanusharma** [comment]
> Are you attempting to load a contact with the GUID `xxxxxxxx-xxxx-x...`?

I had masked the ContactID 

```
XeroPHP\Remote\Exception\ForbiddenException: You are not permitted to access this resource in /var/www/html/project_dev/vendor/calcinai/xero-php/src/XeroPHP/Remote/Response.php:127
Stack trace:
#0 /var/www/html/project_dev/vendor/calcinai/xero-php/src/XeroPHP/Remote/Request.php(119): XeroPHP\Remote\Response->parse()
#1 /var/www/html/project_dev/vendor/calcinai/xero-php/src/XeroPHP/Application.php(200): XeroPHP\Remote\Request->send()
#2 /var/www/html/projcet_dev/vendor/langleyfoxall/xero-laravel/src/Wrappers/QueryWrapper.php(102): XeroPHP\Application->loadByGUID('\\XeroPHP\\Models...', '53469941-5bb8-4...')
```

**Comment by abhimanusharma** [comment]
@calcinai How to resolve this bug?

**Comment by rodjsta** [comment]
Are you able to access other contacts or other objects? Is your app still connected to Xero?

**Comment by abhimanusharma** [comment]
@rodjsta I am not sure, but I am sending access token, Tenant Id, client id and client secret with every request, xero object is returning the correct object but could not able to get the contact or list of contacts. Same error is there.

**Comment by Josh-G** [comment]
> not able to get the contact or list of contacts

You aren't able to pull any contacts at all? 
If you decode your access token, can you definitely see the contacts scope in the `scope` array?
The access token is a JWT and can be decoded by standard JWT tools (for example https://jwt.io/ or any local jwt tool)

**Comment by abhimanusharma** [comment]
@Josh-G Yes, I have contacts in my scope, I am not able to get contacts at all.

**Comment by wilr** [comment]
@abhimanusharma I just came across the same issue and our issue was that I was naively using `$tenant->id` rather than `$tenant->tenantId`.  Once I changed the code to use `tenantId` the error disappeared.
